services:
  pg:
    image: postgres:latest
    container_name: pg
    env_file:
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - ./init/pg:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DATABASE} && PGPASSWORD=${PG_PASSWORD} psql -U ${PG_USER} -d ${PG_NAME} -c \"SELECT 1 FROM public.health_check WHERE status = 'ready';\" | grep -q 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
